# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Ankit Solanki
paginate:       5
baseurl:        "/tale"
url:            "https://techcentaur.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Ankit Solanki
  #url:          http://chester.how
  email:        ankit03june@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/techcentaur/tale

# Gems
gems:
  - jekyll-paginate
